### ISSUE TITLE
2021 Games Incorrect Starting QBs

### ISSUE THREAD

**Issue by AdamKonefal** [nflverse/nfldata#18]
Seems like there's 4 instances where starting QB is incorrect. I can't find the code where this is generated, but these starting QBs have 0 pass attempts in the game per the nflfastR pbp.

- 2021_13_DAL_NO - Trevor Siemian -> Taysom Hill
- 2021_13_ARI_CHI - Colt McCoy -> Kyler Murray
- 2021_14_NYG_LAC - Daniel Jones -> Mike Glennon
- 2021_17_DET_SEA - Jared Goff -> Tim Boyle

**Comment by leesharpe** [comment]
QBs have been updated
