### ISSUE TITLE
Incorrect QB For 2022_02_IND_JAX

### ISSUE THREAD

**Issue by JoshBailey** [nflverse/nfldata#19]
Within [games.csv](https://raw.githubusercontent.com/nflverse/nfldata/master/data/games.csv) for 2022_02_IND_JAX Carson Wentz is listed as the Indy QB in both the name and ID fields. I'm not clear on how this file is generated exactly or else I'd submit a PR to fix it myself. Thanks!

**Comment by leesharpe** [comment]
Fixed in next automated update
