### ISSUE TITLE
The spread line is reversed[

### ISSUE THREAD

**Issue by deganza** [nflverse/nfldata#21]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

The spread_line column is reversed! Instead of -7 you write 7 and so on.

### Describe the solution you'd like

Please adjust the lines

**Comment by tanho63** [comment]
spread_line is documented here https://nflreadr.nflverse.com/articles/dictionary_schedules.html and cannot be changed for backwards compatibility with people’s scripts.

**Comment by deganza** [comment]
Hi Tan Ho

From where did you scrape the wind info?

Regards

Dennis Ganzaroli
Data Scientist

Follow me on Medium <https://deganza11.medium.com/>, Linkedin <https://www.linkedin.com/in/dennis-ganzaroli-17785222/>, Twitter <https://twitter.com/DennisGanzaroli> or Youtube <https://www.youtube.com/channel/UC39MAcTapOXZcibqHmfN3nA>

My Projects are on: KNIME-Hub <https://hub.knime.com/deganza/spaces/Public/latest/>, Tableau-Public <https://public.tableau.com/profile/dennis.ganzaroli#!/> and github <https://github.com/deganza>

**Comment by deganza** [comment]
Hello Tan-Ho

Maybe of interested for you:

In this article I show how to integrate the NFL weather data to get better predictions:

https://medium.com/low-code-for-advanced-data-science/winning-nfl-betting-with-knime-wind-data-and-regression-analysis-0535db8e0d1a￼
Winning NFL Betting with KNIME, Wind Data and Regression Analysis
medium.com


Regards
Dennis

Dennis Ganzaroli
Data Scientist

Follow me on Medium <https://deganza11.medium.com/>, Linkedin <https://www.linkedin.com/in/dennis-ganzaroli-17785222/>, Twitter <https://twitter.com/DennisGanzaroli> or Youtube <https://www.youtube.com/channel/UC39MAcTapOXZcibqHmfN3nA>

My Projects are on: KNIME-Hub <https://hub.knime.com/deganza/spaces/Public/latest/>, Tableau-Public <https://public.tableau.com/profile/dennis.ganzaroli#!/> and github <https://github.com/deganza>
