### ISSUE TITLE
Wrap in a package

### ISSUE THREAD

**Issue by jthomasmock** [nflverse/nfldata#5]
Hi Lee,

Before sharing this widely I wanted to get your approval to wrap these scripts as a package.

I have done this minimally already [here](https://github.com/jthomasmock/nflscrapRextra) but haven't shared it with anyone. This should make it easier for people to consistently apply functions and work with the data, just as sourcing your scripts has done but with a package format now.

Thanks!
Tom

**Comment by matthewdwood82** [comment]
Looking for help getting these helper functions packaged? I am looking for some NFL projects to bang on and improve my R skills, with a little steerage.
